#!/usr/bin/env python3
# One-shot: convert the IIGS ROM 01 binary into a C++ array embedded in flash.
import sys

src = r"C:\Users\lucia\repos\emu6502\resources\Apple IIGS ROM 01 - 342-0077-B.bin"
out_cpp = r"C:\Users\lucia\repos\emu6502\src\iigs\iigs_rom01.cpp"
out_h   = r"C:\Users\lucia\repos\emu6502\src\iigs\iigs_rom01.h"

data = open(src, "rb").read()
assert len(data) == 131072, "expected 128KB ROM 01, got %d" % len(data)

with open(out_h, "w") as f:
    f.write("// iigs_rom01.h - embedded Apple IIGS ROM 01 (342-0077-B), 128KB. Generated by gen_rom.py.\n")
    f.write("// Lives in flash (.rodata). ROM banks: $FE = bytes 0..0xFFFF, $FF = bytes 0x10000..0x1FFFF.\n")
    f.write("#pragma once\n")
    f.write("extern const unsigned char iigsRom01[131072];\n")
    f.write("extern const unsigned int  iigsRom01_len;\n")

with open(out_cpp, "w") as f:
    f.write('#include "iigs_rom01.h"\n')
    f.write("const unsigned char iigsRom01[131072] = {\n")
    for i in range(0, len(data), 20):
        f.write(",".join("0x%02x" % b for b in data[i:i+20]) + ",\n")
    f.write("};\n")
    f.write("const unsigned int iigsRom01_len = 131072;\n")

print("wrote %s (%d lines) and %s" % (out_cpp, (len(data)+19)//20, out_h))
