// iigs_rom01.h - embedded Apple IIGS ROM 01 (342-0077-B), 128KB. Generated by gen_rom.py.
// Lives in flash (.rodata). ROM banks: $FE = bytes 0..0xFFFF, $FF = bytes 0x10000..0x1FFFF.
#pragma once
extern const unsigned char iigsRom01[131072];
extern const unsigned int  iigsRom01_len;
